version: "1.0"
services:
  aspnet-app:
    image: pmi-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    container_name: pmi-app
    restart: unless-stopped
    volumes:
      - ./bin/Debug/net8.0:/app
